-- +goose Up
CREATE TABLE users(
    id uuid PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    name TEXT UNIQUE
);

-- +goose Down
DROP TABLE users;